// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dbstore

import (
	"database/sql"
)

type Album struct {
	ID     int64
	Title  string
	Year   float64
	TypeID sql.NullInt64
}

type Song struct {
	ID      int64
	Title   string
	AlbumID float64
}

type Type struct {
	ID   int64
	Name string
}
