// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: randomsong.sql

package dbstore

import (
	"context"
)

const getRandomSong = `-- name: GetRandomSong :one
SELECT id, title, album_id FROM song ORDER BY RANDOM() LIMIT 1
`

func (q *Queries) GetRandomSong(ctx context.Context) (Song, error) {
	row := q.db.QueryRowContext(ctx, getRandomSong)
	var i Song
	err := row.Scan(&i.ID, &i.Title, &i.AlbumID)
	return i, err
}
