name: Deploy Site To Github Pages

on:
  workflow_dispatch:
  push:
    paths:
      - 'web/**'
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

# One deployment at a time
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.136.5
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
      - name: Setup GitHub Pages
        id: pages
        uses: actions/configure-pages@v5
      - uses: actions/setup-node@v3
        with:
          node-version: '^23.1.0'
      - run: npm install
      - run: npm run tailwind:build
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%d-%m-%Y')"
      - name: Build Configuration File
        run: jq -n env > config.json
        env:
          TMBGBOT_LASTUPDATED: ${{ steps.date.outputs.date }}
          TMBGBOT_VERSION: ${{ steps.get-latest-tag.outputs.tag }}
          TMBGBOT_COMMIT: ${{ github.sha }}
      - run: ejs web/src/config.ejs -f config.json -o web/src/config.js
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./web
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
